package model;
// Generated 2017/7/17 下午 10:08:25 by Hibernate Tools 4.3.1



/**
 * GameMember generated by hbm2java
 */
public class GameMember  implements java.io.Serializable {


     private Integer id;
     private String top;
     private String acount;
     private String pwd;
     private Integer member;
     private String name;
     private Integer status;
     private String money;
     private Integer credit;
     private String date;
     private String onTime;
     private Integer level;
     private String open;
     private Integer moneyTemp;
     private Integer creditTemp;

    public GameMember() {
    }

    public GameMember(String top, String acount, String pwd, Integer member, String name, Integer status, String money, Integer credit, String date, String onTime, Integer level, String open, Integer moneyTemp, Integer creditTemp) {
       this.top = top;
       this.acount = acount;
       this.pwd = pwd;
       this.member = member;
       this.name = name;
       this.status = status;
       this.money = money;
       this.credit = credit;
       this.date = date;
       this.onTime = onTime;
       this.level = level;
       this.open = open;
       this.moneyTemp = moneyTemp;
       this.creditTemp = creditTemp;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTop() {
        return this.top;
    }
    
    public void setTop(String top) {
        this.top = top;
    }
    public String getAcount() {
        return this.acount;
    }
    
    public void setAcount(String acount) {
        this.acount = acount;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public Integer getMember() {
        return this.member;
    }
    
    public void setMember(Integer member) {
        this.member = member;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getMoney() {
        return this.money;
    }
    
    public void setMoney(String money) {
        this.money = money;
    }
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getOnTime() {
        return this.onTime;
    }
    
    public void setOnTime(String onTime) {
        this.onTime = onTime;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
    public String getOpen() {
        return this.open;
    }
    
    public void setOpen(String open) {
        this.open = open;
    }
    public Integer getMoneyTemp() {
        return this.moneyTemp;
    }
    
    public void setMoneyTemp(Integer moneyTemp) {
        this.moneyTemp = moneyTemp;
    }
    public Integer getCreditTemp() {
        return this.creditTemp;
    }
    
    public void setCreditTemp(Integer creditTemp) {
        this.creditTemp = creditTemp;
    }




}


